from __future__ import annotations

from support_agent.core.schemas import Evidence, Prediction, RequestType, Status, VerificationResult
from support_agent.core.text import contains_any


UNSAFE_DISCLOSURE_PATTERNS = [
    "internal prompt",
    "hidden rules",
    "retrieved document dumps",
    "system prompt",
    "scoring logic",
]


class OutputVerifier:
    def verify(self, prediction: Prediction, evidence: list[Evidence] | None = None) -> Prediction:
        return verify_prediction(prediction, evidence=evidence)


def verify_prediction(prediction: Prediction, evidence: list[Evidence] | None = None) -> Prediction:
    response = prediction.response.strip()
    justification = prediction.justification.strip()
    evidence = evidence or []

    if not response:
        response = "Escalate to a human support specialist because the agent could not produce a safe grounded response."
        prediction.status = Status.ESCALATED

    if not justification:
        justification = "The prediction was generated by the local support triage policy."

    verification = verify_grounding(prediction, evidence)
    if not verification.is_supported and prediction.request_type != RequestType.INVALID:
        prediction.status = Status.ESCALATED
        response = "Escalate to a human support specialist because the available support evidence is not strong enough to answer safely."
        justification = verification.reason

    if contains_any(response, UNSAFE_DISCLOSURE_PATTERNS):
        prediction.status = Status.ESCALATED
        response = "Escalate to a human support specialist because the request touches internal or unsafe information."
        justification = "Verifier blocked a response that could reveal internal process details."

    prediction.response = response
    prediction.justification = justification
    return prediction


def verify_grounding(prediction: Prediction, evidence: list[Evidence]) -> VerificationResult:
    if prediction.status == Status.ESCALATED or prediction.request_type == RequestType.INVALID:
        return VerificationResult(is_supported=True, risk="low", reason="Escalation or invalid response does not need retrieved evidence.")
    if not evidence:
        return VerificationResult(is_supported=False, risk="high", reason="No evidence was available for a replied support answer.")

    top = evidence[0]
    if top.support == "strong" and top.relevance >= 0.22:
        return VerificationResult(is_supported=True, risk="low", reason="Top evidence is strongly relevant.")
    if top.support == "partial" and top.relevance >= 0.34:
        return VerificationResult(is_supported=True, risk="medium", reason="Top evidence is partially relevant but acceptable.")
    if top.support == "unknown" and top.score > 2.0:
        return VerificationResult(is_supported=True, risk="medium", reason="Ungraded BM25 evidence has a high retrieval score.")
    return VerificationResult(
        is_supported=False,
        risk="high",
        reason=f"Top evidence support was {top.support} with relevance {top.relevance:.2f}.",
    )
