from __future__ import annotations

from .schemas import Prediction, Status


def verify_prediction(prediction: Prediction) -> Prediction:
    response = prediction.response.strip()
    justification = prediction.justification.strip()
    if not response:
        response = "Escalate to a human support specialist because the agent could not produce a safe grounded response."
        prediction.status = Status.ESCALATED
    if not justification:
        justification = "The prediction was generated by the local support triage policy."
    prediction.response = response
    prediction.justification = justification
    return prediction
